# Generated by Django 2.0.7 on 2018-07-22 06:12

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('price', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Current Price')),
                ('show_registration', models.BooleanField(db_index=True, default=True)),
                ('show_hotels', models.BooleanField(db_index=True, default=True)),
                ('registration_link', models.URLField(blank=True, help_text='Uber registration URL', null=True)),
                ('hotel_link', models.URLField(blank=True, help_text='Hotel booking URL', null=True)),
                ('api_url', models.URLField(blank=True, help_text='Event Uber API url', verbose_name='API Url')),
                ('api_token', models.CharField(blank=True, max_length=48, verbose_name='Uber API Token')),
                ('event_name', models.CharField(blank=True, max_length=64, verbose_name='Name')),
                ('org_name', models.CharField(blank=True, max_length=64, verbose_name='Organization Name')),
                ('year', models.CharField(blank=True, max_length=4)),
                ('epoch', models.DateTimeField(blank=True, null=True)),
                ('eschaton', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=128, verbose_name='Venue Name')),
                ('venue_address', models.CharField(blank=True, max_length=128, verbose_name='Venue Address')),
                ('at_the_con', models.BooleanField(default=False)),
                ('post_con', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('homepage_template_name', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='event',
            name='event',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.EventPage'),
        ),
    ]
