# Generated by Django 2.0.7 on 2018-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='refresh',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
