# Generated by Django 2.0.5 on 2018-06-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='api_token',
            field=models.CharField(default='2a0af59b-260c-4050-a31f-0e85d9f669f2', max_length=48, verbose_name='Uber API Token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='api_url',
            field=models.URLField(default='https://labs2018.uber.magfest.org/uber/jsonrpc/', help_text='Event Uber API url', verbose_name='API Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='at_the_con',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='epoch',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='event_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='event_type',
            field=models.CharField(choices=[('prod', 'Production'), ('dev', 'Development')], default='prod', max_length=8, verbose_name='Event Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='org_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='post_con',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='venue',
            field=models.CharField(blank=True, max_length=128, verbose_name='Venue Name'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='venue_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Venue Address'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
