# Generated by Django 2.0.5 on 2018-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_headline',
            field=models.CharField(default='Super CoolCon', help_text='Event introduction headline', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(default='Weeeeeee', help_text='Event introduction paragraph', max_length=255),
            preserve_default=False,
        ),
    ]
