# Generated by Django 2.0.5 on 2018-05-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180519_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(help_text='Event introduction paragraph', max_length=512),
        ),
    ]
