# Generated by Django 2.0.5 on 2018-05-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180520_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.TextField(help_text='Event introduction paragraph'),
        ),
    ]
